services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: djangobnb
    ports:
      - "5433:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/djnagoserver
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    environment:
      - DATABASE=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db

volumes:
  postgres_data:
